import Head from 'next/head';
import Image from 'next/image';
import {Inter} from '@next/font/google';
import styles from '@/styles/Home.module.css';
import {auth, provider, db} from './_app';
import {signInWithPopup, signOut} from 'firebase/auth';
import {doc, setDoc, getDoc, getDocs, collection} from 'firebase/firestore';
import {useEffect} from 'react';
import {useAuthState} from 'react-firebase-hooks/auth';
const inter = Inter({subsets: ['latin']});

export default function Home() {
	const [user, loading] = useAuthState(auth);

	const signInWithGoogle = (event: React.MouseEvent<HTMLElement>) => {
		event.preventDefault();
		signInWithPopup(auth, provider).then((result) => {
			const docRef = doc(db, 'users', result.user.uid);
			const user = result.user;

			try {
				setDoc(docRef, {
					name: result.user.displayName,
					email: result.user.email,
					photo: result.user.photoURL,
				});
			} catch (e) {
				console.log(e);
			}
			console.log(result);
		});
	};

	const logOut = (event: React.MouseEvent<HTMLElement>) => {
		event.preventDefault();
		signOut(auth).then(() => {
			console.log('sign out');
		});
	};

	useEffect(() => {
		console.log(user);
	}, [user, loading]);

	const getProducts = async () => {
		const productsSnap = await getDocs(collection(db, 'products'));
		productsSnap.forEach((product) => {
			console.log(product.data());
		});
	};

	const getProductById = async (id: string) => {
		const productsDoc = doc(db, 'products', id);
		const productsSnap = await getDoc(productsDoc);
		console.log(productsSnap.data());
	};

	useEffect(() => {
		// getProductById('SbO69CbJ6q9QOhAIJw66');

		getProducts();
	}, []);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link
					rel='icon'
					href='/favicon.ico'
				/>
			</Head>
			<main className={styles.main}>
				<div className={styles.description}>
					<p>
						Get started by editing&nbsp;
						<code className={styles.code}>src/pages/index.tsx</code>
					</p>
					{user ? (
						<button onClick={logOut}>logout</button>
					) : (
						<button onClick={signInWithGoogle}>login</button>
					)}
					<div>
						<a
							href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
							target='_blank'
							rel='noopener noreferrer'
						>
							By{' '}
							<Image
								src='/vercel.svg'
								alt='Vercel Logo'
								className={styles.vercelLogo}
								width={100}
								height={24}
								priority
							/>
						</a>
					</div>
				</div>

				<div className={styles.center}>
					<Image
						className={styles.logo}
						src='/next.svg'
						alt='Next.js Logo'
						width={180}
						height={37}
						priority
					/>
					<div className={styles.thirteen}>
						<Image
							src='/thirteen.svg'
							alt='13'
							width={40}
							height={31}
							priority
						/>
					</div>
				</div>

				<div className={styles.grid}>
					<a
						href='https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
						className={styles.card}
						target='_blank'
						rel='noopener noreferrer'
					>
						<h2 className={inter.className}>
							Docs <span>-&gt;</span>
						</h2>
						<p className={inter.className}>
							Find in-depth information about Next.js features and&nbsp;API.
						</p>
					</a>

					<a
						href='https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
						className={styles.card}
						target='_blank'
						rel='noopener noreferrer'
					>
						<h2 className={inter.className}>
							Learn <span>-&gt;</span>
						</h2>
						<p className={inter.className}>
							Learn about Next.js in an interactive course with&nbsp;quizzes!
						</p>
					</a>

					<a
						href='https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
						className={styles.card}
						target='_blank'
						rel='noopener noreferrer'
					>
						<h2 className={inter.className}>
							Templates <span>-&gt;</span>
						</h2>
						<p className={inter.className}>
							Discover and deploy boilerplate example Next.js&nbsp;projects.
						</p>
					</a>

					<a
						href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
						className={styles.card}
						target='_blank'
						rel='noopener noreferrer'
					>
						<h2 className={inter.className}>
							Deploy <span>-&gt;</span>
						</h2>
						<p className={inter.className}>
							Instantly deploy your Next.js site to a shareable URL
							with&nbsp;Vercel.
						</p>
					</a>
				</div>
			</main>
		</>
	);
}
